set(_CATKIN_CURRENT_PACKAGE "left_arm_config")
set(left_arm_config_VERSION "0.3.0")
set(left_arm_config_MAINTAINER "Jennie <zjl93128@hotmail.com>")
set(left_arm_config_PACKAGE_FORMAT "1")
set(left_arm_config_BUILD_DEPENDS "left_arm_description")
set(left_arm_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro" "left_arm_description")
set(left_arm_config_BUILDTOOL_DEPENDS "catkin")
set(left_arm_config_BUILDTOOL_EXPORT_DEPENDS )
set(left_arm_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro" "left_arm_description")
set(left_arm_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro" "left_arm_description")
set(left_arm_config_TEST_DEPENDS )
set(left_arm_config_DOC_DEPENDS )
set(left_arm_config_URL_WEBSITE "http://moveit.ros.org/")
set(left_arm_config_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(left_arm_config_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(left_arm_config_DEPRECATED "")