set(_CATKIN_CURRENT_PACKAGE "motors_moveit")
set(motors_moveit_VERSION "1.0.0")
set(motors_moveit_MAINTAINER "Ali Paikan <ali.paikan@luxai.com>")
set(motors_moveit_PACKAGE_FORMAT "1")
set(motors_moveit_BUILD_DEPENDS )
set(motors_moveit_BUILD_EXPORT_DEPENDS )
set(motors_moveit_BUILDTOOL_DEPENDS "catkin")
set(motors_moveit_BUILDTOOL_EXPORT_DEPENDS )
set(motors_moveit_EXEC_DEPENDS )
set(motors_moveit_RUN_DEPENDS )
set(motors_moveit_TEST_DEPENDS )
set(motors_moveit_DOC_DEPENDS )
set(motors_moveit_URL_WEBSITE "http://www.luxai.com/")
set(motors_moveit_URL_BUGTRACKER "")
set(motors_moveit_URL_REPOSITORY "")
set(motors_moveit_DEPRECATED "")