set(_CATKIN_CURRENT_PACKAGE "qt_control")
set(qt_control_VERSION "0.0.0")
set(qt_control_MAINTAINER "jennie <jennie@todo.todo>")
set(qt_control_PACKAGE_FORMAT "2")
set(qt_control_BUILD_DEPENDS "rospy" "std_msgs")
set(qt_control_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(qt_control_BUILDTOOL_DEPENDS "catkin")
set(qt_control_BUILDTOOL_EXPORT_DEPENDS )
set(qt_control_EXEC_DEPENDS "rospy" "std_msgs")
set(qt_control_RUN_DEPENDS "rospy" "std_msgs")
set(qt_control_TEST_DEPENDS )
set(qt_control_DOC_DEPENDS )
set(qt_control_URL_WEBSITE "")
set(qt_control_URL_BUGTRACKER "")
set(qt_control_URL_REPOSITORY "")
set(qt_control_DEPRECATED "")