set(_CATKIN_CURRENT_PACKAGE "qtrobot_config")
set(qtrobot_config_VERSION "0.3.0")
set(qtrobot_config_MAINTAINER "Jennie <jianlingzou93@gmail.com>")
set(qtrobot_config_PACKAGE_FORMAT "1")
set(qtrobot_config_BUILD_DEPENDS )
set(qtrobot_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro")
set(qtrobot_config_BUILDTOOL_DEPENDS "catkin")
set(qtrobot_config_BUILDTOOL_EXPORT_DEPENDS )
set(qtrobot_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro")
set(qtrobot_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro")
set(qtrobot_config_TEST_DEPENDS )
set(qtrobot_config_DOC_DEPENDS )
set(qtrobot_config_URL_WEBSITE "http://moveit.ros.org/")
set(qtrobot_config_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(qtrobot_config_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(qtrobot_config_DEPRECATED "")