set(_CATKIN_CURRENT_PACKAGE "new_qt")
set(new_qt_VERSION "0.3.0")
set(new_qt_MAINTAINER "zou <jianlingzou93@gmail.com>")
set(new_qt_PACKAGE_FORMAT "1")
set(new_qt_BUILD_DEPENDS )
set(new_qt_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro")
set(new_qt_BUILDTOOL_DEPENDS "catkin")
set(new_qt_BUILDTOOL_EXPORT_DEPENDS )
set(new_qt_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro")
set(new_qt_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro")
set(new_qt_TEST_DEPENDS )
set(new_qt_DOC_DEPENDS )
set(new_qt_URL_WEBSITE "http://moveit.ros.org/")
set(new_qt_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(new_qt_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(new_qt_DEPRECATED "")