set(_CATKIN_CURRENT_PACKAGE "qtrobot_ikfast_left_arm_plugin")
set(qtrobot_ikfast_left_arm_plugin_VERSION "0.0.0")
set(qtrobot_ikfast_left_arm_plugin_MAINTAINER "apaikan <apaikan@todo.todo>")
set(qtrobot_ikfast_left_arm_plugin_PACKAGE_FORMAT "2")
set(qtrobot_ikfast_left_arm_plugin_BUILD_DEPENDS "moveit_core" "liblapack-dev" "roscpp" "tf_conversions" "pluginlib")
set(qtrobot_ikfast_left_arm_plugin_BUILD_EXPORT_DEPENDS )
set(qtrobot_ikfast_left_arm_plugin_BUILDTOOL_DEPENDS "catkin")
set(qtrobot_ikfast_left_arm_plugin_BUILDTOOL_EXPORT_DEPENDS )
set(qtrobot_ikfast_left_arm_plugin_EXEC_DEPENDS "moveit_core" "liblapack-dev" "roscpp" "tf_conversions" "pluginlib")
set(qtrobot_ikfast_left_arm_plugin_RUN_DEPENDS "moveit_core" "liblapack-dev" "roscpp" "tf_conversions" "pluginlib")
set(qtrobot_ikfast_left_arm_plugin_TEST_DEPENDS )
set(qtrobot_ikfast_left_arm_plugin_DOC_DEPENDS )
set(qtrobot_ikfast_left_arm_plugin_URL_WEBSITE "")
set(qtrobot_ikfast_left_arm_plugin_URL_BUGTRACKER "")
set(qtrobot_ikfast_left_arm_plugin_URL_REPOSITORY "")
set(qtrobot_ikfast_left_arm_plugin_DEPRECATED "")