// Generated by gencpp from file qt_nuitrack_app/FaceInfo.msg
// DO NOT EDIT!


#ifndef QT_NUITRACK_APP_MESSAGE_FACEINFO_H
#define QT_NUITRACK_APP_MESSAGE_FACEINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_nuitrack_app
{
template <class ContainerAllocator>
struct FaceInfo_
{
  typedef FaceInfo_<ContainerAllocator> Type;

  FaceInfo_()
    : id(0)
    , gender()
    , age_years(0)
    , age_type()
    , emotion_neutral(0.0)
    , emotion_angry(0.0)
    , emotion_happy(0.0)
    , emotion_surprise(0.0)
    , rectangle()
    , left_eye()
    , right_eye()
    , angles()  {
    }
  FaceInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , gender(_alloc)
    , age_years(0)
    , age_type(_alloc)
    , emotion_neutral(0.0)
    , emotion_angry(0.0)
    , emotion_happy(0.0)
    , emotion_surprise(0.0)
    , rectangle(_alloc)
    , left_eye(_alloc)
    , right_eye(_alloc)
    , angles(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _gender_type;
  _gender_type gender;

   typedef int32_t _age_years_type;
  _age_years_type age_years;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _age_type_type;
  _age_type_type age_type;

   typedef double _emotion_neutral_type;
  _emotion_neutral_type emotion_neutral;

   typedef double _emotion_angry_type;
  _emotion_angry_type emotion_angry;

   typedef double _emotion_happy_type;
  _emotion_happy_type emotion_happy;

   typedef double _emotion_surprise_type;
  _emotion_surprise_type emotion_surprise;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _rectangle_type;
  _rectangle_type rectangle;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _left_eye_type;
  _left_eye_type left_eye;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _right_eye_type;
  _right_eye_type right_eye;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> const> ConstPtr;

}; // struct FaceInfo_

typedef ::qt_nuitrack_app::FaceInfo_<std::allocator<void> > FaceInfo;

typedef boost::shared_ptr< ::qt_nuitrack_app::FaceInfo > FaceInfoPtr;
typedef boost::shared_ptr< ::qt_nuitrack_app::FaceInfo const> FaceInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qt_nuitrack_app

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'qt_nuitrack_app': ['/home/jennie/irecheck/iReCheck/QT_ws/src/qt_nuitrack_app/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b210720ecbe10f5a0a7a3911214f766a";
  }

  static const char* value(const ::qt_nuitrack_app::FaceInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb210720ecbe10f5aULL;
  static const uint64_t static_value2 = 0x0a7a3911214f766aULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_nuitrack_app/FaceInfo";
  }

  static const char* value(const ::qt_nuitrack_app::FaceInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#std_msgs/Header header\n\
int32 id\n\
string gender\n\
int32 age_years\n\
string age_type\n\
float64 emotion_neutral\n\
float64 emotion_angry\n\
float64 emotion_happy\n\
float64 emotion_surprise\n\
#normalized screen coordinates of a face rectangle in the image (x, y, w, h)\n\
float64[] rectangle\n\
#normalized coordinates of the center of a person’s left eye (x,y)\n\
float64[] left_eye\n\
#normalized coordinates of the center of a person’s right eye (x,y)\n\
float64[] right_eye\n\
#face orientation angles in degrees (yaw, pitch, roll)\n\
float64[] angles\n\
";
  }

  static const char* value(const ::qt_nuitrack_app::FaceInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.gender);
      stream.next(m.age_years);
      stream.next(m.age_type);
      stream.next(m.emotion_neutral);
      stream.next(m.emotion_angry);
      stream.next(m.emotion_happy);
      stream.next(m.emotion_surprise);
      stream.next(m.rectangle);
      stream.next(m.left_eye);
      stream.next(m.right_eye);
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_nuitrack_app::FaceInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_nuitrack_app::FaceInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "gender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.gender);
    s << indent << "age_years: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age_years);
    s << indent << "age_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.age_type);
    s << indent << "emotion_neutral: ";
    Printer<double>::stream(s, indent + "  ", v.emotion_neutral);
    s << indent << "emotion_angry: ";
    Printer<double>::stream(s, indent + "  ", v.emotion_angry);
    s << indent << "emotion_happy: ";
    Printer<double>::stream(s, indent + "  ", v.emotion_happy);
    s << indent << "emotion_surprise: ";
    Printer<double>::stream(s, indent + "  ", v.emotion_surprise);
    s << indent << "rectangle[]" << std::endl;
    for (size_t i = 0; i < v.rectangle.size(); ++i)
    {
      s << indent << "  rectangle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rectangle[i]);
    }
    s << indent << "left_eye[]" << std::endl;
    for (size_t i = 0; i < v.left_eye.size(); ++i)
    {
      s << indent << "  left_eye[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.left_eye[i]);
    }
    s << indent << "right_eye[]" << std::endl;
    for (size_t i = 0; i < v.right_eye.size(); ++i)
    {
      s << indent << "  right_eye[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.right_eye[i]);
    }
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_NUITRACK_APP_MESSAGE_FACEINFO_H
