// Generated by gencpp from file qt_nuitrack_app/GestureInfo.msg
// DO NOT EDIT!


#ifndef QT_NUITRACK_APP_MESSAGE_GESTUREINFO_H
#define QT_NUITRACK_APP_MESSAGE_GESTUREINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_nuitrack_app
{
template <class ContainerAllocator>
struct GestureInfo_
{
  typedef GestureInfo_<ContainerAllocator> Type;

  GestureInfo_()
    : id(0)
    , name()  {
    }
  GestureInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GestureInfo_

typedef ::qt_nuitrack_app::GestureInfo_<std::allocator<void> > GestureInfo;

typedef boost::shared_ptr< ::qt_nuitrack_app::GestureInfo > GestureInfoPtr;
typedef boost::shared_ptr< ::qt_nuitrack_app::GestureInfo const> GestureInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qt_nuitrack_app

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'qt_nuitrack_app': ['/home/jennie/irecheck/iReCheck/QT_ws/src/qt_nuitrack_app/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fe5a440459dcada9c353c016dfb49d2";
  }

  static const char* value(const ::qt_nuitrack_app::GestureInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fe5a440459dcadaULL;
  static const uint64_t static_value2 = 0x9c353c016dfb49d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_nuitrack_app/GestureInfo";
  }

  static const char* value(const ::qt_nuitrack_app::GestureInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#std_msgs/Header header\n\
int32 id\n\
string name\n\
";
  }

  static const char* value(const ::qt_nuitrack_app::GestureInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GestureInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_nuitrack_app::GestureInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_NUITRACK_APP_MESSAGE_GESTUREINFO_H
