set(_CATKIN_CURRENT_PACKAGE "left_arm_description")
set(left_arm_description_VERSION "0.0.0")
set(left_arm_description_MAINTAINER "jennie <jennie@todo.todo>")
set(left_arm_description_PACKAGE_FORMAT "2")
set(left_arm_description_BUILD_DEPENDS "roscpp" "rospy" "std_msg")
set(left_arm_description_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msg")
set(left_arm_description_BUILDTOOL_DEPENDS "catkin")
set(left_arm_description_BUILDTOOL_EXPORT_DEPENDS )
set(left_arm_description_EXEC_DEPENDS "roscpp" "rospy" "std_msg")
set(left_arm_description_RUN_DEPENDS "roscpp" "rospy" "std_msg")
set(left_arm_description_TEST_DEPENDS )
set(left_arm_description_DOC_DEPENDS )
set(left_arm_description_URL_WEBSITE "")
set(left_arm_description_URL_BUGTRACKER "")
set(left_arm_description_URL_REPOSITORY "")
set(left_arm_description_DEPRECATED "")