// Generated by gencpp from file irecheck/FieldsSrv.msg
// DO NOT EDIT!


#ifndef IRECHECK_MESSAGE_FIELDSSRV_H
#define IRECHECK_MESSAGE_FIELDSSRV_H

#include <ros/service_traits.h>


#include <irecheck/FieldsSrvRequest.h>
#include <irecheck/FieldsSrvResponse.h>


namespace irecheck
{

struct FieldsSrv
{

typedef FieldsSrvRequest Request;
typedef FieldsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FieldsSrv
} // namespace irecheck


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::irecheck::FieldsSrv > {
  static const char* value()
  {
    return "43c0132e6d5bd924f115049e9614e3d9";
  }

  static const char* value(const ::irecheck::FieldsSrv&) { return value(); }
};

template<>
struct DataType< ::irecheck::FieldsSrv > {
  static const char* value()
  {
    return "irecheck/FieldsSrv";
  }

  static const char* value(const ::irecheck::FieldsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::irecheck::FieldsSrvRequest> should match 
// service_traits::MD5Sum< ::irecheck::FieldsSrv > 
template<>
struct MD5Sum< ::irecheck::FieldsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::irecheck::FieldsSrv >::value();
  }
  static const char* value(const ::irecheck::FieldsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::irecheck::FieldsSrvRequest> should match 
// service_traits::DataType< ::irecheck::FieldsSrv > 
template<>
struct DataType< ::irecheck::FieldsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::irecheck::FieldsSrv >::value();
  }
  static const char* value(const ::irecheck::FieldsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::irecheck::FieldsSrvResponse> should match 
// service_traits::MD5Sum< ::irecheck::FieldsSrv > 
template<>
struct MD5Sum< ::irecheck::FieldsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::irecheck::FieldsSrv >::value();
  }
  static const char* value(const ::irecheck::FieldsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::irecheck::FieldsSrvResponse> should match 
// service_traits::DataType< ::irecheck::FieldsSrv > 
template<>
struct DataType< ::irecheck::FieldsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::irecheck::FieldsSrv >::value();
  }
  static const char* value(const ::irecheck::FieldsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IRECHECK_MESSAGE_FIELDSSRV_H
