// Generated by gencpp from file irecheck/FieldsSrvRequest.msg
// DO NOT EDIT!


#ifndef IRECHECK_MESSAGE_FIELDSSRVREQUEST_H
#define IRECHECK_MESSAGE_FIELDSSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace irecheck
{
template <class ContainerAllocator>
struct FieldsSrvRequest_
{
  typedef FieldsSrvRequest_<ContainerAllocator> Type;

  FieldsSrvRequest_()
    {
    }
  FieldsSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::irecheck::FieldsSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irecheck::FieldsSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FieldsSrvRequest_

typedef ::irecheck::FieldsSrvRequest_<std::allocator<void> > FieldsSrvRequest;

typedef boost::shared_ptr< ::irecheck::FieldsSrvRequest > FieldsSrvRequestPtr;
typedef boost::shared_ptr< ::irecheck::FieldsSrvRequest const> FieldsSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irecheck::FieldsSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irecheck

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irecheck::FieldsSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irecheck::FieldsSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irecheck::FieldsSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::irecheck::FieldsSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irecheck/FieldsSrvRequest";
  }

  static const char* value(const ::irecheck::FieldsSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::irecheck::FieldsSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FieldsSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irecheck::FieldsSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::irecheck::FieldsSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IRECHECK_MESSAGE_FIELDSSRVREQUEST_H
