// Generated by gencpp from file irecheck/FieldsSrvResponse.msg
// DO NOT EDIT!


#ifndef IRECHECK_MESSAGE_FIELDSSRVRESPONSE_H
#define IRECHECK_MESSAGE_FIELDSSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace irecheck
{
template <class ContainerAllocator>
struct FieldsSrvResponse_
{
  typedef FieldsSrvResponse_<ContainerAllocator> Type;

  FieldsSrvResponse_()
    : fields()  {
    }
  FieldsSrvResponse_(const ContainerAllocator& _alloc)
    : fields(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fields_type;
  _fields_type fields;





  typedef boost::shared_ptr< ::irecheck::FieldsSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irecheck::FieldsSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FieldsSrvResponse_

typedef ::irecheck::FieldsSrvResponse_<std::allocator<void> > FieldsSrvResponse;

typedef boost::shared_ptr< ::irecheck::FieldsSrvResponse > FieldsSrvResponsePtr;
typedef boost::shared_ptr< ::irecheck::FieldsSrvResponse const> FieldsSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irecheck::FieldsSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irecheck

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irecheck::FieldsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irecheck::FieldsSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irecheck::FieldsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43c0132e6d5bd924f115049e9614e3d9";
  }

  static const char* value(const ::irecheck::FieldsSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43c0132e6d5bd924ULL;
  static const uint64_t static_value2 = 0xf115049e9614e3d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irecheck/FieldsSrvResponse";
  }

  static const char* value(const ::irecheck::FieldsSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string fields\n\
\n\
";
  }

  static const char* value(const ::irecheck::FieldsSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fields);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FieldsSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irecheck::FieldsSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irecheck::FieldsSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "fields: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fields);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRECHECK_MESSAGE_FIELDSSRVRESPONSE_H
