set(_CATKIN_CURRENT_PACKAGE "comportement_control")
set(comportement_control_VERSION "0.0.0")
set(comportement_control_MAINTAINER "jennie <jennie@todo.todo>")
set(comportement_control_PACKAGE_FORMAT "2")
set(comportement_control_BUILD_DEPENDS "rospy" "std_msgs")
set(comportement_control_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(comportement_control_BUILDTOOL_DEPENDS "catkin")
set(comportement_control_BUILDTOOL_EXPORT_DEPENDS )
set(comportement_control_EXEC_DEPENDS "rospy" "std_msgs")
set(comportement_control_RUN_DEPENDS "rospy" "std_msgs")
set(comportement_control_TEST_DEPENDS )
set(comportement_control_DOC_DEPENDS )
set(comportement_control_URL_WEBSITE "")
set(comportement_control_URL_BUGTRACKER "")
set(comportement_control_URL_REPOSITORY "")
set(comportement_control_DEPRECATED "")