# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logindlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginDlg(object):
    def setupUi(self, loginDlg):
        loginDlg.setObjectName("loginDlg")
        loginDlg.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(loginDlg)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 80, 181, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.usrLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usrLineEdit.setObjectName("usrLineEdit")
        self.gridLayout.addWidget(self.usrLineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.usrLineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usrLineEdit_2.setObjectName("usrLineEdit_2")
        self.gridLayout.addWidget(self.usrLineEdit_2, 1, 1, 1, 1)
        self.LoginBtn = QtWidgets.QPushButton(loginDlg)
        self.LoginBtn.setGeometry(QtCore.QRect(140, 210, 99, 27))
        self.LoginBtn.setObjectName("LoginBtn")

        self.retranslateUi(loginDlg)
        QtCore.QMetaObject.connectSlotsByName(loginDlg)

    def retranslateUi(self, loginDlg):
        _translate = QtCore.QCoreApplication.translate
        loginDlg.setWindowTitle(_translate("loginDlg", "Dialog"))
        self.label.setText(_translate("loginDlg", "Nom:"))
        self.label_2.setText(_translate("loginDlg", "Prenom:"))
        self.LoginBtn.setText(_translate("loginDlg", "Login"))
