controller_list:
  - name: fake_head_controller
    joints:
      - HeadYaw
      - HeadPitch
  - name: fake_left_arm_controller
    joints:
      - LeftShoulderPitch
      - LeftShoulderRoll
      - LeftElbowRoll
  - name: fake_right_arm_controller
    joints:
      - RightShoulderPitch
      - RightShoulderRoll
      - RightElbowRoll
initial:  # Define initial robot poses.
  - group: head
    pose: home
  - group: left_arm
    pose: home
  - group: right_arm
    pose: home